<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGeca5d3\websiteProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGeca5d3/websiteProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGeca5d3.legacy');

    return;
}

if (!\class_exists(websiteProdProjectContainer::class, false)) {
    \class_alias(\ContainerGeca5d3\websiteProdProjectContainer::class, websiteProdProjectContainer::class, false);
}

return new \ContainerGeca5d3\websiteProdProjectContainer(array(
    'container.build_hash' => 'Geca5d3',
    'container.build_id' => '7983aa37',
    'container.build_time' => 1532502312,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGeca5d3');
