<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.initializer_manager' shared service.

return $this->services['doctrine_phpcr.initializer_manager'] = new \Doctrine\Bundle\PHPCRBundle\Initializer\InitializerManager(${($_ = isset($this->services['doctrine_phpcr']) ? $this->services['doctrine_phpcr'] : $this->load('getDoctrinePhpcrService.php')) && false ?: '_'});
