<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.twig.content.memoized' shared service.

return $this->services['sulu_website.twig.content.memoized'] = new \Sulu\Bundle\WebsiteBundle\Twig\Content\MemoizedContentTwigExtension(${($_ = isset($this->services['sulu_website.twig.content']) ? $this->services['sulu_website.twig.content'] : $this->load('getSuluWebsite_Twig_ContentService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.cache.memoize']) ? $this->services['sulu_core.cache.memoize'] : $this->load('getSuluCore_Cache_MemoizeService.php')) && false ?: '_'}, 1);
