<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.twig.navigation' shared service.

return $this->services['sulu_website.twig.navigation'] = new \Sulu\Bundle\WebsiteBundle\Twig\Navigation\NavigationTwigExtension(${($_ = isset($this->services['sulu.content.mapper']) ? $this->services['sulu.content.mapper'] : $this->load('getSulu_Content_MapperService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_website.navigation_mapper']) ? $this->services['sulu_website.navigation_mapper'] : $this->load('getSuluWebsite_NavigationMapperService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.webspace.request_analyzer']) ? $this->services['sulu_core.webspace.request_analyzer'] : $this->getSuluCore_Webspace_RequestAnalyzerService()) && false ?: '_'});
