<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.single_select' shared service.

return $this->services['sulu.content.type.single_select'] = new \Sulu\Bundle\ContentBundle\Content\Types\SingleSelect('SuluContentBundle:Template:content-types/single_select.html.twig');
