<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_http_cache.proxy_client.varnish' shared service.

return $this->services['sulu_http_cache.proxy_client.varnish'] = new \FOS\HttpCache\ProxyClient\Varnish(array(), NULL);
