<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.sitemap.pool' shared service.

return $this->services['sulu_website.sitemap.pool'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\SitemapProviderPool(array('pages' => ${($_ = isset($this->services['sulu_website.sitemap.pages_provider']) ? $this->services['sulu_website.sitemap.pages_provider'] : $this->load('getSuluWebsite_Sitemap_PagesProviderService.php')) && false ?: '_'}));
