<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.array_serialization_visitor' shared service.

return $this->services['sulu_core.array_serialization_visitor'] = new \Sulu\Component\Serializer\ArraySerializationVisitor(${($_ = isset($this->services['jms_serializer.naming_strategy']) ? $this->services['jms_serializer.naming_strategy'] : $this->load('getJmsSerializer_NamingStrategyService.php')) && false ?: '_'});
