<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.content_navigation_registry' shared service.

$this->services['sulu_admin.content_navigation_registry'] = $instance = new \Sulu\Bundle\AdminBundle\Navigation\ContentNavigationRegistry($this);

$instance->addContentNavigationProvider('contact', 'sulu_contact.contact_content_navigation_provider');
$instance->addContentNavigationProvider('account', 'sulu_contact.account_content_navigation_provider');
$instance->addContentNavigationProvider('media', 'sulu_media.admin.content_navigation_provider');
$instance->addContentNavigationProvider('roles', 'sulu_security.roles_content_navigation_provider');
$instance->addContentNavigationProvider('contact', 'sulu_security.contacts_content_navigation_provider');
$instance->addContentNavigationProvider('category', 'sulu_category.content_navigation_provider');
$instance->addContentNavigationProvider('snippet', 'sulu_snippet.content_navigation_provider');
$instance->addContentNavigationProvider('webspace', 'sulu_snippet.webspace_navigation_provider');
$instance->addContentNavigationProvider('content', 'sulu_content.content_navigation_provider');
$instance->addContentNavigationProvider('webspace', 'sulu_content.webspace_navigation_provider');
$instance->addContentNavigationProvider('roles', 'sulu_content.roles_content_navigation_provider');
$instance->addContentNavigationProvider('webspace', 'sulu_website.webspace_navigation_provider');
$instance->addContentNavigationProvider('webspace', 'sulu_custom_urls.webspace_navigation_provider');

return $instance;
