<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.resource_locator' shared service.

return $this->services['sulu.content.type.resource_locator'] = new \Sulu\Component\Content\Types\ResourceLocator('SuluContentBundle:Template:content-types/resource_locator.html.twig');
