<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.extension.seo' shared service.

return $this->services['sulu_content.extension.seo'] = new \Sulu\Bundle\ContentBundle\Content\Structure\SeoStructureExtension();
