<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.js_config' shared service.

return $this->services['sulu_admin.js_config'] = new \Sulu\Bundle\AdminBundle\Admin\JsConfig('sulu_admin.widget_groups', array());
