<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.js_config' shared service.

return $this->services['sulu_media.js_config'] = new \Sulu\Bundle\AdminBundle\Admin\JsConfig('sulu-media', array('permissions' => ${($_ = isset($this->services['sulu_security.access_control_manager']) ? $this->services['sulu_security.access_control_manager'] : $this->load('getSuluSecurity_AccessControlManagerService.php')) && false ?: '_'}->getUserPermissions(${($_ = isset($this->services['sulu_media.security_context']) ? $this->services['sulu_media.security_context'] : $this->services['sulu_media.security_context'] = new \Sulu\Component\Security\Authorization\SecurityCondition('sulu.media.collections')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}->getToken()->getUser()), 'maxFilesize' => 256, 'adobeCreativeKey' => NULL, 'formats' => $this->parameters['sulu_media.image.formats']));
