<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.extension.excerpt' shared service.

return $this->services['sulu_content.extension.excerpt'] = new \Sulu\Bundle\ContentBundle\Content\Structure\ExcerptStructureExtension(${($_ = isset($this->services['sulu.content.structure_manager']) ? $this->services['sulu.content.structure_manager'] : $this->getSulu_Content_StructureManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu.content.type_manager']) ? $this->services['sulu.content.type_manager'] : $this->getSulu_Content_TypeManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.export.manager']) ? $this->services['sulu_content.export.manager'] : $this->load('getSuluContent_Export_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.import.manager']) ? $this->services['sulu_content.import.manager'] : $this->load('getSuluContent_Import_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_search.search.factory']) ? $this->services['sulu_search.search.factory'] : $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory()) && false ?: '_'});
