<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.webspace.serializer.event_subscriber' shared service.

return $this->services['sulu_content.webspace.serializer.event_subscriber'] = new \Sulu\Bundle\ContentBundle\EventListener\WebspaceSerializeEventSubscriber(${($_ = isset($this->services['sulu_core.webspace.webspace_manager']) ? $this->services['sulu_core.webspace.webspace_manager'] : $this->getSuluCore_Webspace_WebspaceManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.webspace.url_provider']) ? $this->services['sulu_core.webspace.url_provider'] : $this->load('getSuluCore_Webspace_UrlProviderService.php')) && false ?: '_'}, 'prod');
