<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.teaser.serializer.event_subscriber' shared service.

return $this->services['sulu_content.teaser.serializer.event_subscriber'] = new \Sulu\Bundle\ContentBundle\EventListener\TeaserSerializeEventSubscriber(${($_ = isset($this->services['sulu_media.media_manager']) ? $this->services['sulu_media.media_manager'] : $this->getSuluMedia_MediaManagerService()) && false ?: '_'});
