<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.jsconfig.apps' shared service.

return $this->services['sulu_content.jsconfig.apps'] = new \Sulu\Bundle\WebsocketBundle\Admin\AppJsConfig(${($_ = isset($this->services['sulu_websocket.manager']) ? $this->services['sulu_websocket.manager'] : $this->load('getSuluWebsocket_ManagerService.php')) && false ?: '_'});
