<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.admin' shared service.

return $this->services['sulu_preview.admin'] = new \Sulu\Bundle\PreviewBundle\Admin\PreviewAdmin('Sulu');
