<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_custom_urls.repository' shared service.

return $this->services['sulu_custom_urls.repository'] = new \Sulu\Component\CustomUrl\Repository\CustomUrlRepository(${($_ = isset($this->services['sulu.phpcr.session']) ? $this->services['sulu.phpcr.session'] : $this->getSulu_Phpcr_SessionService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.content_repository']) ? $this->services['sulu_content.content_repository'] : $this->getSuluContent_ContentRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_custom_urls.domain_generator']) ? $this->services['sulu_custom_urls.domain_generator'] : $this->load('getSuluCustomUrls_DomainGeneratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_security.user_manager']) ? $this->services['sulu_security.user_manager'] : $this->load('getSuluSecurity_UserManagerService.php')) && false ?: '_'});
