<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_hash.request_hash_checker' shared service.

return $this->services['sulu_hash.request_hash_checker'] = new \Sulu\Component\Hash\RequestHashChecker(${($_ = isset($this->services['sulu_hash.auditable_hasher']) ? $this->services['sulu_hash.auditable_hasher'] : $this->services['sulu_hash.auditable_hasher'] = new \Sulu\Component\Hash\AuditableHasher()) && false ?: '_'});
