<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.resolver.parameter' shared service.

return $this->services['sulu_website.resolver.parameter'] = new \Sulu\Bundle\WebsiteBundle\Resolver\ParameterResolver(${($_ = isset($this->services['sulu_website.resolver.structure']) ? $this->services['sulu_website.resolver.structure'] : $this->load('getSuluWebsite_Resolver_StructureService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_website.resolver.request_analyzer']) ? $this->services['sulu_website.resolver.request_analyzer'] : $this->load('getSuluWebsite_Resolver_RequestAnalyzerService.php')) && false ?: '_'});
