<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.twig_extension.media' shared service.

return $this->services['sulu_media.twig_extension.media'] = new \Sulu\Bundle\MediaBundle\Twig\MediaTwigExtension(${($_ = isset($this->services['sulu_media.media_manager']) ? $this->services['sulu_media.media_manager'] : $this->getSuluMedia_MediaManagerService()) && false ?: '_'});
