<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.twig.sitemap.memoized' shared service.

return $this->services['sulu_website.twig.sitemap.memoized'] = new \Sulu\Bundle\WebsiteBundle\Twig\Sitemap\MemoizedSitemapTwigExtension(${($_ = isset($this->services['sulu_website.twig.sitemap']) ? $this->services['sulu_website.twig.sitemap'] : $this->load('getSuluWebsite_Twig_SitemapService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.cache.memoize']) ? $this->services['sulu_core.cache.memoize'] : $this->load('getSuluCore_Cache_MemoizeService.php')) && false ?: '_'}, 1);
