<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.loader' shared service.

$this->services['twig.loader'] = $instance = new \Symfony\Bundle\TwigBundle\Loader\FilesystemLoader(${($_ = isset($this->services['templating.locator']) ? $this->services['templating.locator'] : $this->load('getTemplating_LocatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['templating.name_parser']) ? $this->services['templating.name_parser'] : $this->services['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'})) && false ?: '_'}, $this->targetDirs[4]);

$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle/Resources/views'), 'Framework');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle/Resources/views'), '!Framework');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle/Resources/views'), 'Twig');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle/Resources/views'), '!Twig');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\swiftmailer-bundle/Resources/views'), 'Swiftmailer');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\swiftmailer-bundle/Resources/views'), '!Swiftmailer');
$instance->addPath(($this->targetDirs[4].'\\vendor\\doctrine\\doctrine-bundle/Resources/views'), 'Doctrine');
$instance->addPath(($this->targetDirs[4].'\\vendor\\doctrine\\doctrine-bundle/Resources/views'), '!Doctrine');
$instance->addPath(($this->targetDirs[4].'\\vendor\\doctrine\\phpcr-bundle/Resources/views'), 'DoctrinePHPCR');
$instance->addPath(($this->targetDirs[4].'\\vendor\\doctrine\\phpcr-bundle/Resources/views'), '!DoctrinePHPCR');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContactBundle/Resources/views'), 'SuluContact');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContactBundle/Resources/views'), '!SuluContact');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\MediaBundle/Resources/views'), 'SuluMedia');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\MediaBundle/Resources/views'), '!SuluMedia');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\SecurityBundle/Resources/views'), 'SuluSecurity');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\SecurityBundle/Resources/views'), '!SuluSecurity');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\CategoryBundle/Resources/views'), 'SuluCategory');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\CategoryBundle/Resources/views'), '!SuluCategory');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\SnippetBundle/Resources/views'), 'SuluSnippet');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\SnippetBundle/Resources/views'), '!SuluSnippet');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContentBundle/Resources/views'), 'SuluContent');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContentBundle/Resources/views'), '!SuluContent');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\TagBundle/Resources/views'), 'SuluTag');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\TagBundle/Resources/views'), '!SuluTag');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\WebsiteBundle/Resources/views'), 'SuluWebsite');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\WebsiteBundle/Resources/views'), '!SuluWebsite');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\LocationBundle/Resources/views'), 'SuluLocation');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\LocationBundle/Resources/views'), '!SuluLocation');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\RouteBundle/Resources/views'), 'SuluRoute');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\RouteBundle/Resources/views'), '!SuluRoute');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\SecurityBundle/Resources/views'), 'Security');
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\SecurityBundle/Resources/views'), '!Security');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\community-bundle/Resources/views'), 'SuluCommunity');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\community-bundle/Resources/views'), '!SuluCommunity');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AdminBundle/Resources/views'), 'SuluAdmin');
$instance->addPath(($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\AdminBundle/Resources/views'), '!SuluAdmin');
$instance->addPath(($this->targetDirs[4].'\\app/Resources/views'));
$instance->addPath(($this->targetDirs[4].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bridge\\Twig/Resources/views/Form'));

return $instance;
