<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHbnafim\adminDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHbnafim/adminDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHbnafim.legacy');

    return;
}

if (!\class_exists(adminDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHbnafim\adminDevDebugProjectContainer::class, adminDevDebugProjectContainer::class, false);
}

return new \ContainerHbnafim\adminDevDebugProjectContainer(array(
    'container.build_hash' => 'Hbnafim',
    'container.build_id' => '95e0be99',
    'container.build_time' => 1531906626,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHbnafim');
