<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjbdbnh\adminDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjbdbnh/adminDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRjbdbnh.legacy');

    return;
}

if (!\class_exists(adminDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRjbdbnh\adminDevDebugProjectContainer::class, adminDevDebugProjectContainer::class, false);
}

return new \ContainerRjbdbnh\adminDevDebugProjectContainer(array(
    'container.build_hash' => 'Rjbdbnh',
    'container.build_id' => 'e5b7b158',
    'container.build_time' => 1532511923,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjbdbnh');
