<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHes7xda\adminDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHes7xda/adminDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHes7xda.legacy');

    return;
}

if (!\class_exists(adminDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHes7xda\adminDevDebugProjectContainer::class, adminDevDebugProjectContainer::class, false);
}

return new \ContainerHes7xda\adminDevDebugProjectContainer(array(
    'container.build_hash' => 'Hes7xda',
    'container.build_id' => '0e7d6ebb',
    'container.build_time' => 1532334498,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHes7xda');
