<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.time' shared service.

return $this->services['sulu.content.type.time'] = new \Sulu\Bundle\ContentBundle\Content\Types\Time('SuluContentBundle:Template:content-types/time.html.twig');
