<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hateoas.generator.registry' shared service.

return $this->services['hateoas.generator.registry'] = new \Hateoas\UrlGenerator\UrlGeneratorRegistry(${($_ = isset($this->services['hateoas.generator.symfony']) ? $this->services['hateoas.generator.symfony'] : $this->load('getHateoas_Generator_SymfonyService.php')) && false ?: '_'});
