<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.twig.link' shared service.

return $this->services['hateoas.twig.link'] = new \Hateoas\Twig\Extension\LinkExtension(${($_ = isset($this->services['hateoas.helper.link']) ? $this->services['hateoas.helper.link'] : $this->load('getHateoas_Helper_LinkService.php')) && false ?: '_'});
