<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.command.reindex' shared service.

return $this->services['massive_search.command.reindex'] = new \Massive\Bundle\SearchBundle\Command\ReindexCommand(${($_ = isset($this->services['massive_search.reindex.resume_manager']) ? $this->services['massive_search.reindex.resume_manager'] : $this->services['massive_search.reindex.resume_manager'] = new \Massive\Bundle\SearchBundle\Search\Reindex\ResumeManager()) && false ?: '_'}, ${($_ = isset($this->services['massive_search.search_manager']) ? $this->services['massive_search.search_manager'] : $this->load('getMassiveSearch_SearchManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['massive_search.reindex.provider_registry']) ? $this->services['massive_search.reindex.provider_registry'] : $this->load('getMassiveSearch_Reindex_ProviderRegistryService.php')) && false ?: '_'}, 'prod');
