<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.field_evaluator' shared service.

return $this->services['massive_search.metadata.field_evaluator'] = new \Massive\Bundle\SearchBundle\Search\Metadata\FieldEvaluator(${($_ = isset($this->services['massive_search.expression_language']) ? $this->services['massive_search.expression_language'] : $this->services['massive_search.expression_language'] = new \Massive\Bundle\SearchBundle\Search\ExpressionLanguage\MassiveSearchExpressionLanguage()) && false ?: '_'});
