<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.command.migrate' shared service.

return $this->services['phpcr_migrations.command.migrate'] = new \DTL\Bundle\PhpcrMigrations\Command\MigrateCommand(${($_ = isset($this->services['phpcr_migrations.migrator_factory']) ? $this->services['phpcr_migrations.migrator_factory'] : $this->load('getPhpcrMigrations_MigratorFactoryService.php')) && false ?: '_'}, $this);
