<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.disposition_type.resolver' shared service.

return $this->services['sulu_media.disposition_type.resolver'] = new \Sulu\Bundle\MediaBundle\Media\DispositionType\DispositionTypeResolver('attachment', array(), array());
