<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_tag.reference_store.tag' shared service.

return $this->services['sulu_tag.reference_store.tag'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore();
