<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.js_config.server' shared service.

return $this->services['sulu_content.js_config.server'] = new \Sulu\Bundle\AdminBundle\Admin\JsConfig('sulu.websocket.server', array('enabled' => false, 'port' => 9876, 'httpHost' => 'sulu.lo'));
