<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.export.manager' shared service.

$this->services['sulu_content.export.manager'] = $instance = new \Sulu\Component\Export\Manager\ExportManager(${($_ = isset($this->services['sulu.content.type_manager']) ? $this->services['sulu.content.type_manager'] : $this->getSulu_Content_TypeManagerService()) && false ?: '_'});

$instance->add('text_line', '1.2.xliff', array('translate' => true));
$instance->add('text_area', '1.2.xliff', array('translate' => true));
$instance->add('text_editor', '1.2.xliff', array('translate' => true));
$instance->add('resource_locator', '1.2.xliff', array('translate' => false));
$instance->add('block', '1.2.xliff', array('translate' => false));
$instance->add('contact', '1.2.xliff', array('translate' => false));
$instance->add('media_selection', '1.2.xliff', array('translate' => false));
$instance->add('category_list', '1.2.xliff', array('translate' => false));
$instance->add('snippet', '1.2.xliff', array('translate' => false));
$instance->add('smart_content', '1.2.xliff', array('translate' => false));
$instance->add('teaser_selection', '1.2.xliff', array('translate' => false));
$instance->add('internal_links', '1.2.xliff', array('translate' => false));
$instance->add('single_internal_link', '1.2.xliff', array('translate' => false));
$instance->add('phone', '1.2.xliff', array('translate' => false));
$instance->add('password', '1.2.xliff', array('translate' => false));
$instance->add('url', '1.2.xliff', array('translate' => false));
$instance->add('email', '1.2.xliff', array('translate' => false));
$instance->add('date', '1.2.xliff', array('translate' => false));
$instance->add('time', '1.2.xliff', array('translate' => false));
$instance->add('color', '1.2.xliff', array('translate' => false));
$instance->add('checkbox', '1.2.xliff', array('translate' => false));
$instance->add('multiple_select', '1.2.xliff', array('translate' => false));
$instance->add('single_select', '1.2.xliff', array('translate' => false));
$instance->add('tag_list', '1.2.xliff', array('translate' => false));
$instance->add('location', '1.2.xliff', array('translate' => false));

return $instance;
