<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.twig.navigation.memoized' shared service.

return $this->services['sulu_website.twig.navigation.memoized'] = new \Sulu\Bundle\WebsiteBundle\Twig\Navigation\MemoizedNavigationTwigExtension(${($_ = isset($this->services['sulu_website.twig.navigation']) ? $this->services['sulu_website.twig.navigation'] : $this->load('getSuluWebsite_Twig_NavigationService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.cache.memoize']) ? $this->services['sulu_core.cache.memoize'] : $this->load('getSuluCore_Cache_MemoizeService.php')) && false ?: '_'}, 1);
