<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.content.snippet' shared service.

return $this->services['sulu_snippet.content.snippet'] = new \Sulu\Bundle\SnippetBundle\Content\SnippetContent(${($_ = isset($this->services['sulu_snippet.default_snippet.manager']) ? $this->services['sulu_snippet.default_snippet.manager'] : $this->load('getSuluSnippet_DefaultSnippet_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_snippet.resolver']) ? $this->services['sulu_snippet.resolver'] : $this->load('getSuluSnippet_ResolverService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_snippet.reference_store.snippet']) ? $this->services['sulu_snippet.reference_store.snippet'] : $this->services['sulu_snippet.reference_store.snippet'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()) && false ?: '_'}, true, 'SuluSnippetBundle:Template:content-types/snippet.html.twig');
