<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_contact.twig' shared service.

return $this->services['sulu_contact.twig'] = new \Sulu\Bundle\ContactBundle\Twig\ContactTwigExtension(${($_ = isset($this->services['sulu_contact.twig.cache']) ? $this->services['sulu_contact.twig.cache'] : $this->services['sulu_contact.twig.cache'] = new \Doctrine\Common\Cache\ArrayCache()) && false ?: '_'}, ${($_ = isset($this->services['sulu.repository.contact']) ? $this->services['sulu.repository.contact'] : $this->load('getSulu_Repository_ContactService.php')) && false ?: '_'});
