<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.permission_listener' shared service.

return $this->services['sulu_content.permission_listener'] = new \Sulu\Bundle\ContentBundle\Search\EventListener\PermissionListener(${($_ = isset($this->services['sulu_document_manager.document_manager']) ? $this->services['sulu_document_manager.document_manager'] : $this->load('getSuluDocumentManager_DocumentManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['massive_search.search_manager']) ? $this->services['massive_search.search_manager'] : $this->load('getMassiveSearch_SearchManagerService.php')) && false ?: '_'});
