<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.phpcr_access_control_provider' shared service.

return $this->services['sulu_security.phpcr_access_control_provider'] = new \Sulu\Component\Security\Authorization\AccessControl\PhpcrAccessControlProvider(${($_ = isset($this->services['sulu_document_manager.document_manager']) ? $this->services['sulu_document_manager.document_manager'] : $this->load('getSuluDocumentManager_DocumentManagerService.php')) && false ?: '_'}, $this->parameters['permissions']);
