<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_build.builder.virtual.dev' shared service.

return $this->services['massive_build.builder.virtual.dev'] = new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('dev', array(0 => 'database', 1 => 'fixtures', 2 => 'phpcr', 3 => 'user', 4 => 'phpcr_migrations', 5 => 'system_collections'));
