<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_build.builder.virtual.prod' shared service.

return $this->services['massive_build.builder.virtual.prod'] = new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('prod', array(0 => 'database', 1 => 'phpcr', 2 => 'fixtures', 3 => 'phpcr_migrations', 4 => 'system_collections'));
