<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.format_cache_clearer' shared service.

$this->services['sulu_media.format_cache_clearer'] = $instance = new \Sulu\Bundle\MediaBundle\Media\FormatCache\FormatCacheClearer();

$instance->add(${($_ = isset($this->services['sulu_media.format_cache']) ? $this->services['sulu_media.format_cache'] : $this->getSuluMedia_FormatCacheService()) && false ?: '_'}, 'local');

return $instance;
