<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_location.controller.geoloactor' shared service.

return $this->services['sulu_location.controller.geoloactor'] = new \Sulu\Bundle\LocationBundle\Controller\GeolocatorController(${($_ = isset($this->services['sulu_location.geolocator.manager']) ? $this->services['sulu_location.geolocator.manager'] : $this->load('getSuluLocation_Geolocator_ManagerService.php')) && false ?: '_'});
