<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.compat.serializer.handler.page_bridge' shared service.

return $this->services['sulu_content.compat.serializer.handler.page_bridge'] = new \Sulu\Component\Content\Compat\Serializer\PageBridgeHandler(${($_ = isset($this->services['sulu_document_manager.document_inspector']) ? $this->services['sulu_document_manager.document_inspector'] : $this->getSuluDocumentManager_DocumentInspectorService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.compat.structure.legacy_property_factory']) ? $this->services['sulu_content.compat.structure.legacy_property_factory'] : $this->getSuluContent_Compat_Structure_LegacyPropertyFactoryService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.structure.factory']) ? $this->services['sulu_content.structure.factory'] : $this->getSuluContent_Structure_FactoryService()) && false ?: '_'});
