<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.teaser.manager' shared service.

return $this->services['sulu_content.teaser.manager'] = new \Sulu\Bundle\ContentBundle\Teaser\TeaserManager(${($_ = isset($this->services['sulu_content.teaser.provider_pool']) ? $this->services['sulu_content.teaser.provider_pool'] : $this->load('getSuluContent_Teaser_ProviderPoolService.php')) && false ?: '_'});
