<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_websocket.manager' shared service.

$this->services['sulu_websocket.manager'] = $instance = new \Sulu\Component\Websocket\RatchetAppManager(9876, 'sulu.lo', '0.0.0.0');

$instance->add('/admin', ${($_ = isset($this->services['sulu_websocket.admin.message_dispatcher.app']) ? $this->services['sulu_websocket.admin.message_dispatcher.app'] : $this->load('getSuluWebsocket_Admin_MessageDispatcher_AppService.php')) && false ?: '_'}, array(0 => '*'), NULL);

return $instance;
