<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.smart_content.data_provider.media.repository' shared service.

return $this->services['sulu_media.smart_content.data_provider.media.repository'] = new \Sulu\Bundle\MediaBundle\Entity\MediaDataProviderRepository(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_media.media_manager']) ? $this->services['sulu_media.media_manager'] : $this->getSuluMedia_MediaManagerService()) && false ?: '_'}, 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', 'SuluMediaBundle:Collection');
