<?php

namespace Proxies\__CG__\Sulu\Bundle\SecurityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Group extends \Sulu\Bundle\SecurityBundle\Entity\Group implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'lft', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'rgt', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'depth', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'name', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'created', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'changed', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'id', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'children', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'userGroups', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'parent', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'roles', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'changer', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'creator', 'apiBasePath', 'apiPath'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'lft', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'rgt', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'depth', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'name', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'created', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'changed', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'id', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'children', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'userGroups', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'parent', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'roles', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'changer', '' . "\0" . 'Sulu\\Bundle\\SecurityBundle\\Entity\\Group' . "\0" . 'creator', 'apiBasePath', 'apiPath'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Group $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLft($lft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLft', [$lft]);

        return parent::setLft($lft);
    }

    /**
     * {@inheritDoc}
     */
    public function getLft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLft', []);

        return parent::getLft();
    }

    /**
     * {@inheritDoc}
     */
    public function setRgt($rgt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRgt', [$rgt]);

        return parent::setRgt($rgt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRgt', []);

        return parent::getRgt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepth($depth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepth', [$depth]);

        return parent::setDepth($depth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepth', []);

        return parent::getDepth();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getChanged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanged', []);

        return parent::getChanged();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addChildren(\Sulu\Bundle\SecurityBundle\Entity\Group $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChildren', [$children]);

        return parent::addChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChildren(\Sulu\Bundle\SecurityBundle\Entity\Group $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChildren', [$children]);

        return parent::removeChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserGroup(\Sulu\Bundle\SecurityBundle\Entity\UserGroup $userGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserGroup', [$userGroups]);

        return parent::addUserGroup($userGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserGroup(\Sulu\Bundle\SecurityBundle\Entity\UserGroup $userGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserGroup', [$userGroups]);

        return parent::removeUserGroup($userGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroups', []);

        return parent::getUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Sulu\Bundle\SecurityBundle\Entity\Group $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\Sulu\Component\Security\Authentication\RoleInterface $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$roles]);

        return parent::addRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\Sulu\Component\Security\Authentication\RoleInterface $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$roles]);

        return parent::removeRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanger(\Sulu\Component\Security\Authentication\UserInterface $changer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanger', [$changer]);

        return parent::setChanger($changer);
    }

    /**
     * {@inheritDoc}
     */
    public function getChanger()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanger', []);

        return parent::getChanger();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\Sulu\Component\Security\Authentication\UserInterface $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', [$creator]);

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', []);

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinks', []);

        return parent::getLinks();
    }

    /**
     * {@inheritDoc}
     */
    public function createSelfLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createSelfLink', []);

        return parent::createSelfLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getApiPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiPath', []);

        return parent::getApiPath();
    }

    /**
     * {@inheritDoc}
     */
    public function hasApiPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasApiPath', []);

        return parent::hasApiPath();
    }

}
