<?php

namespace Proxies\__CG__\Sulu\Bundle\ContactBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \Sulu\Bundle\ContactBundle\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'street', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'number', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'addition', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'zip', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'city', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'state', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'id', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'addressType', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'country', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'primaryAddress', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'deliveryAddress', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'billingAddress', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'postboxNumber', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'postboxPostcode', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'postboxCity', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'contactAddresses', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'accountAddresses', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'note', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'title', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'latitude', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'longitude'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'street', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'number', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'addition', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'zip', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'city', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'state', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'id', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'addressType', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'country', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'primaryAddress', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'deliveryAddress', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'billingAddress', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'postboxNumber', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'postboxPostcode', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'postboxCity', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'contactAddresses', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'accountAddresses', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'note', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'title', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'latitude', '' . "\0" . 'Sulu\\Bundle\\ContactBundle\\Entity\\Address' . "\0" . 'longitude'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddition($addition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddition', [$addition]);

        return parent::setAddition($addition);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddition', []);

        return parent::getAddition();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', [$zip]);

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', []);

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressType(\Sulu\Bundle\ContactBundle\Entity\AddressType $addressType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressType', [$addressType]);

        return parent::setAddressType($addressType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressType', []);

        return parent::getAddressType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\Sulu\Bundle\ContactBundle\Entity\Country $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryAddress($primaryAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryAddress', [$primaryAddress]);

        return parent::setPrimaryAddress($primaryAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryAddress', []);

        return parent::getPrimaryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryAddress($deliveryAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryAddress', [$deliveryAddress]);

        return parent::setDeliveryAddress($deliveryAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAddress', []);

        return parent::getDeliveryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress($billingAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', [$billingAddress]);

        return parent::setBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', []);

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostboxNumber($postboxNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostboxNumber', [$postboxNumber]);

        return parent::setPostboxNumber($postboxNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostboxNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostboxNumber', []);

        return parent::getPostboxNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostboxPostcode($postboxPostcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostboxPostcode', [$postboxPostcode]);

        return parent::setPostboxPostcode($postboxPostcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostboxPostcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostboxPostcode', []);

        return parent::getPostboxPostcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostboxCity($postboxCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostboxCity', [$postboxCity]);

        return parent::setPostboxCity($postboxCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostboxCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostboxCity', []);

        return parent::getPostboxCity();
    }

    /**
     * {@inheritDoc}
     */
    public function addContactAddress(\Sulu\Bundle\ContactBundle\Entity\ContactAddress $contactAddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContactAddress', [$contactAddresses]);

        return parent::addContactAddress($contactAddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContactAddress(\Sulu\Bundle\ContactBundle\Entity\ContactAddress $contactAddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContactAddress', [$contactAddresses]);

        return parent::removeContactAddress($contactAddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactAddresses', []);

        return parent::getContactAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccountAddress(\Sulu\Bundle\ContactBundle\Entity\AccountAddress $accountAddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccountAddress', [$accountAddresses]);

        return parent::addAccountAddress($accountAddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccountAddress(\Sulu\Bundle\ContactBundle\Entity\AccountAddress $accountAddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccountAddress', [$accountAddresses]);

        return parent::removeAccountAddress($accountAddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountAddresses', []);

        return parent::getAccountAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRelations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRelations', []);

        return parent::hasRelations();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

}
