<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.admin.jackalope.repository.live' shared service.

return $this->services['doctrine_phpcr.admin.jackalope.repository.live'] = ${($_ = isset($this->services['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal']) ? $this->services['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] : $this->services['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] = new \Jackalope\RepositoryFactoryDoctrineDBAL()) && false ?: '_'}->getRepository(array('jackalope.doctrine_dbal_connection' => ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}, 'jackalope.check_login_on_server' => false));
