<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.provider.chain' shared service.

return $this->services['massive_search.metadata.provider.chain'] = new \Massive\Bundle\SearchBundle\Search\Metadata\Provider\ChainProvider(array(0 => ${($_ = isset($this->services['massive_search.metadata.provider.default']) ? $this->services['massive_search.metadata.provider.default'] : $this->load('getMassiveSearch_Metadata_Provider_DefaultService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['sulu_content.search.metadata.provider.structure']) ? $this->services['sulu_content.search.metadata.provider.structure'] : $this->load('getSuluContent_Search_Metadata_Provider_StructureService.php')) && false ?: '_'}));
