<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.command.init' shared service.

return $this->services['massive_search.command.init'] = new \Massive\Bundle\SearchBundle\Command\InitCommand(${($_ = isset($this->services['massive_search.adapter.zend_lucene']) ? $this->services['massive_search.adapter.zend_lucene'] : $this->load('getMassiveSearch_Adapter_ZendLuceneService.php')) && false ?: '_'});
