<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.reindex.provider_registry' shared service.

$this->services['massive_search.reindex.provider_registry'] = $instance = new \Massive\Bundle\SearchBundle\Search\Reindex\ReindexProviderRegistry();

$instance->addProvider('doctrine_orm', ${($_ = isset($this->services['massive_search.reindex.provider.doctrine_orm']) ? $this->services['massive_search.reindex.provider.doctrine_orm'] : $this->load('getMassiveSearch_Reindex_Provider_DoctrineOrmService.php')) && false ?: '_'});
$instance->addProvider('sulu_structure', ${($_ = isset($this->services['sulu_content.search.reindex.structure_provider']) ? $this->services['sulu_content.search.reindex.structure_provider'] : $this->load('getSuluContent_Search_Reindex_StructureProviderService.php')) && false ?: '_'});

return $instance;
