<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.command.initialize' shared service.

return $this->services['phpcr_migrations.command.initialize'] = new \DTL\Bundle\PhpcrMigrations\Command\InitializeCommand(${($_ = isset($this->services['phpcr_migrations.migrator_factory']) ? $this->services['phpcr_migrations.migrator_factory'] : $this->load('getPhpcrMigrations_MigratorFactoryService.php')) && false ?: '_'});
