<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.provider.doctrine' shared service.

return $this->services['sulu_core.list_builder.metadata.provider.doctrine'] = new \Sulu\Component\Rest\ListBuilder\Metadata\Provider\MetadataProvider(${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.doctrine.factory']) ? $this->services['sulu_core.list_builder.metadata.provider.doctrine.factory'] : $this->load('getSuluCore_ListBuilder_Metadata_Provider_Doctrine_FactoryService.php')) && false ?: '_'});
