<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_location.geolocator.service.google' shared service.

return $this->services['sulu_location.geolocator.service.google'] = new \Sulu\Bundle\LocationBundle\Geolocator\Service\GoogleGeolocator(${($_ = isset($this->services['sulu_location.geolocator.guzzle.client']) ? $this->services['sulu_location.geolocator.guzzle.client'] : $this->services['sulu_location.geolocator.guzzle.client'] = new \GuzzleHttp\Client()) && false ?: '_'}, '');
