<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.provider.general.driver.xml' shared service.

return $this->services['sulu_core.list_builder.metadata.provider.general.driver.xml'] = new \Sulu\Component\Rest\ListBuilder\Metadata\General\Driver\XmlDriver(${($_ = isset($this->services['sulu_core.list_builder.metadata.file_locator']) ? $this->services['sulu_core.list_builder.metadata.file_locator'] : $this->services['sulu_core.list_builder.metadata.file_locator'] = new \Metadata\Driver\FileLocator(array('Sulu\\Bundle\\ContactBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContactBundle/Resources/config/list-builder'), 'Sulu\\Bundle\\MediaBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\MediaBundle/Resources/config/list-builder'), 'Sulu\\Bundle\\CategoryBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\CategoryBundle/Resources/config/list-builder')))) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.list_builder.metadata.parameter_bag']) ? $this->services['sulu_core.list_builder.metadata.parameter_bag'] : $this->load('getSuluCore_ListBuilder_Metadata_ParameterBagService.php')) && false ?: '_'});
