<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_tag.content.type.tag_list' shared service.

return $this->services['sulu_tag.content.type.tag_list'] = new \Sulu\Bundle\TagBundle\Content\Types\TagList(${($_ = isset($this->services['sulu_tag.tag_manager']) ? $this->services['sulu_tag.tag_manager'] : $this->getSuluTag_TagManagerService()) && false ?: '_'}, 'SuluTagBundle:Template:content-types/tag_list.html.twig');
