<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_location.geolocator.manager' shared service.

$this->services['sulu_location.geolocator.manager'] = $instance = new \Sulu\Bundle\LocationBundle\Geolocator\GeolocatorManager($this);

$instance->register('nominatim', 'sulu_location.gelocator.service.nominatim');
$instance->register('google', 'sulu_location.geolocator.service.google');

return $instance;
