<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.teaser.provider.content' shared service.

return $this->services['sulu_content.teaser.provider.content'] = new \Sulu\Bundle\ContentBundle\Teaser\ContentTeaserProvider(${($_ = isset($this->services['massive_search.search_manager']) ? $this->services['massive_search.search_manager'] : $this->load('getMassiveSearch_SearchManagerService.php')) && false ?: '_'});
