<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.sitemap.xml_dumper' shared service.

return $this->services['sulu_website.sitemap.xml_dumper'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\XmlSitemapDumper(${($_ = isset($this->services['sulu_website.sitemap.xml_renderer']) ? $this->services['sulu_website.sitemap.xml_renderer'] : $this->load('getSuluWebsite_Sitemap_XmlRendererService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_website.sitemap.pool']) ? $this->services['sulu_website.sitemap.pool'] : $this->load('getSuluWebsite_Sitemap_PoolService.php')) && false ?: '_'}, ${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()) && false ?: '_'}, ($this->targetDirs[3].'/sitemaps'), NULL);
