<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_custom_urls.url_provider' shared service.

return $this->services['sulu_custom_urls.url_provider'] = new \Sulu\Component\CustomUrl\WebspaceCustomUrlProvider(${($_ = isset($this->services['sulu_custom_urls.manager']) ? $this->services['sulu_custom_urls.manager'] : $this->getSuluCustomUrls_ManagerService()) && false ?: '_'});
