<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.color' shared service.

return $this->services['sulu.content.type.color'] = new \Sulu\Bundle\ContentBundle\Content\Types\Color('SuluContentBundle:Template:content-types/color.html.twig');
