<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.js_config.webspace_input_types' shared service.

return $this->services['sulu_content.js_config.webspace_input_types'] = new \Sulu\Bundle\ContentBundle\Admin\WebspaceInputTypesJsConfig(${($_ = isset($this->services['sulu_core.webspace.webspace_manager']) ? $this->services['sulu_core.webspace.webspace_manager'] : $this->getSuluCore_Webspace_WebspaceManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu.content.resource_locator.strategy_pool']) ? $this->services['sulu.content.resource_locator.strategy_pool'] : $this->getSulu_Content_ResourceLocator_StrategyPoolService()) && false ?: '_'});
