<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.rest_helper' shared service.

return $this->services['sulu_core.rest_helper'] = new \Sulu\Component\Rest\RestHelper(${($_ = isset($this->services['sulu_core.list_rest_helper']) ? $this->services['sulu_core.list_rest_helper'] : $this->load('getSuluCore_ListRestHelperService.php')) && false ?: '_'});
