<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.phone' shared service.

return $this->services['sulu.content.type.phone'] = new \Sulu\Bundle\ContentBundle\Content\Types\Phone('SuluContentBundle:Template:content-types/phone.html.twig');
