<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIp3xtrd\adminProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIp3xtrd/adminProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIp3xtrd.legacy');

    return;
}

if (!\class_exists(adminProdProjectContainer::class, false)) {
    \class_alias(\ContainerIp3xtrd\adminProdProjectContainer::class, adminProdProjectContainer::class, false);
}

return new \ContainerIp3xtrd\adminProdProjectContainer(array(
    'container.build_hash' => 'Ip3xtrd',
    'container.build_id' => 'b95cea9c',
    'container.build_time' => 1532503360,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIp3xtrd');
