<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJsor0vn\adminProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJsor0vn/adminProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJsor0vn.legacy');

    return;
}

if (!\class_exists(adminProdProjectContainer::class, false)) {
    \class_alias(\ContainerJsor0vn\adminProdProjectContainer::class, adminProdProjectContainer::class, false);
}

return new \ContainerJsor0vn\adminProdProjectContainer(array(
    'container.build_hash' => 'Jsor0vn',
    'container.build_id' => 'e0032452',
    'container.build_time' => 1532521744,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJsor0vn');
