<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuu40gy\adminProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuu40gy/adminProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIuu40gy.legacy');

    return;
}

if (!\class_exists(adminProdProjectContainer::class, false)) {
    \class_alias(\ContainerIuu40gy\adminProdProjectContainer::class, adminProdProjectContainer::class, false);
}

return new \ContainerIuu40gy\adminProdProjectContainer(array(
    'container.build_hash' => 'Iuu40gy',
    'container.build_id' => 'b41a8d74',
    'container.build_time' => 1531906719,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIuu40gy');
