<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_route.content_type' shared service.

return $this->services['sulu_route.content_type'] = new \Sulu\Bundle\RouteBundle\Content\Type\RouteContentType('SuluRouteBundle:Template:content-types/route.html.twig');
