<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.analytics.manager' shared service.

return $this->services['sulu_website.analytics.manager'] = new \Sulu\Bundle\WebsiteBundle\Analytics\AnalyticsManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_website.analytics.repository']) ? $this->services['sulu_website.analytics.repository'] : $this->load('getSuluWebsite_Analytics_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_website.domains.repository']) ? $this->services['sulu_website.domains.repository'] : $this->load('getSuluWebsite_Domains_RepositoryService.php')) && false ?: '_'});
