<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.http_cache.clearer' shared service.

return $this->services['sulu_website.http_cache.clearer'] = new \Sulu\Bundle\WebsiteBundle\Cache\CacheClearer(${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()) && false ?: '_'}, 'dev', ($this->targetDirs[4].'\\app'), ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, (($this->hasParameter("kernel.var_dir")) ? ($this->getParameter("kernel.var_dir")) : (null)), ${($_ = isset($this->services['sulu_http_cache.proxy_client.symfony']) ? $this->services['sulu_http_cache.proxy_client.symfony'] : $this->services['sulu_http_cache.proxy_client.symfony'] = new \Sulu\Component\HttpCache\ProxyClient\Symfony()) && false ?: '_'});
