<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.preview.kernel_factory' shared service.

return $this->services['sulu_preview.preview.kernel_factory'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory();
