<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.link_tag.js_config' shared service.

return $this->services['sulu_content.link_tag.js_config'] = new \Sulu\Bundle\ContentBundle\Admin\LinkProviderJsConfig(${($_ = isset($this->services['sulu_content.link_tag.provider_pool']) ? $this->services['sulu_content.link_tag.provider_pool'] : $this->getSuluContent_LinkTag_ProviderPoolService()) && false ?: '_'});
