<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.widgets_handler' shared service.

return $this->services['sulu_admin.widgets_handler'] = new \Sulu\Bundle\AdminBundle\Widgets\WidgetsHandler(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, array());
