<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_community.blacklisting.item_manager' shared service.

return $this->services['sulu_community.blacklisting.item_manager'] = new \Sulu\Bundle\CommunityBundle\Manager\BlacklistItemManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_community.blacklisting.item_repository']) ? $this->services['sulu_community.blacklisting.item_repository'] : $this->load('getSuluCommunity_Blacklisting_ItemRepositoryService.php')) && false ?: '_'});
