<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.sulu_websocket' shared service.

return $this->services['doctrine_cache.providers.sulu_websocket'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/sulu/websocket'), NULL, 2);
