<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.expression_language' shared service.

return $this->services['massive_search.expression_language'] = new \Massive\Bundle\SearchBundle\Search\ExpressionLanguage\MassiveSearchExpressionLanguage();
