<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.migrator_factory' shared service.

return $this->services['phpcr_migrations.migrator_factory'] = new \PHPCR\Migrations\MigratorFactory(${($_ = isset($this->services['phpcr_migrations.version_storage']) ? $this->services['phpcr_migrations.version_storage'] : $this->load('getPhpcrMigrations_VersionStorageService.php')) && false ?: '_'}, ${($_ = isset($this->services['phpcr_migrations.version_finder']) ? $this->services['phpcr_migrations.version_finder'] : $this->load('getPhpcrMigrations_VersionFinderService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.decorated_live_session']) ? $this->services['sulu_document_manager.decorated_live_session'] : $this->getSuluDocumentManager_DecoratedLiveSessionService()) && false ?: '_'});
