<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.date' shared service.

return $this->services['sulu.content.type.date'] = new \Sulu\Bundle\ContentBundle\Content\Types\Date('SuluContentBundle:Template:content-types/date.html.twig');
