<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.rememberme.services.simplehash.ma_getraenkeverwaltung' shared service.

return $this->services['security.authentication.rememberme.services.simplehash.ma_getraenkeverwaltung'] = new \Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices(array(0 => ${($_ = isset($this->services['sulu_security.user_provider']) ? $this->services['sulu_security.user_provider'] : $this->load('getSuluSecurity_UserProviderService.php')) && false ?: '_'}), 'ThisTokenIsNotSoSecretChangeIt', 'ma_getraenkeverwaltung', array('lifetime' => 604800, 'path' => '/', 'name' => 'REMEMBERME', 'domain' => NULL, 'secure' => false, 'httponly' => true, 'always_remember_me' => false, 'remember_me_parameter' => '_remember_me'), ${($_ = isset($this->services['monolog.logger.security']) ? $this->services['monolog.logger.security'] : $this->load('getMonolog_Logger_SecurityService.php')) && false ?: '_'});
