<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.document_manager.content_initializer' shared service.

return $this->services['sulu_content.document_manager.content_initializer'] = new \Sulu\Bundle\ContentBundle\DocumentManager\ContentInitializer(${($_ = isset($this->services['doctrine_phpcr']) ? $this->services['doctrine_phpcr'] : $this->getDoctrinePhpcrService()) && false ?: '_'}, 'i18n');
