<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.internal_links' shared service.

return $this->services['sulu.content.type.internal_links'] = new \Sulu\Bundle\ContentBundle\Content\Types\InternalLinks(${($_ = isset($this->services['sulu.content.query_executor']) ? $this->services['sulu.content.query_executor'] : $this->getSulu_Content_QueryExecutorService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.smart_content.data_provider.content.query_builder']) ? $this->services['sulu_content.smart_content.data_provider.content.query_builder'] : $this->load('getSuluContent_SmartContent_DataProvider_Content_QueryBuilderService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.reference_store.content']) ? $this->services['sulu_content.reference_store.content'] : $this->services['sulu_content.reference_store.content'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'}, 'SuluContentBundle:Template:content-types/internal_links.html.twig', false);
