<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.subscriber.behavior.alias' shared service.

$a = ${($_ = isset($this->services['sulu_document_manager.decorated_live_session']) ? $this->services['sulu_document_manager.decorated_live_session'] : $this->getSuluDocumentManager_DecoratedLiveSessionService()) && false ?: '_'};

return $this->services['sulu_document_manager.subscriber.behavior.alias'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Path\AliasFilingSubscriber($a, $a, ${($_ = isset($this->services['sulu_document_manager.metadata_factory.base']) ? $this->services['sulu_document_manager.metadata_factory.base'] : $this->getSuluDocumentManager_MetadataFactory_BaseService()) && false ?: '_'});
