<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.search.metadata.provider.structure' shared service.

return $this->services['sulu_content.search.metadata.provider.structure'] = new \Sulu\Bundle\ContentBundle\Search\Metadata\StructureProvider(${($_ = isset($this->services['sulu_search.search.factory']) ? $this->services['sulu_search.search.factory'] : $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory()) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.metadata_factory']) ? $this->services['sulu_document_manager.metadata_factory'] : $this->getSuluDocumentManager_MetadataFactoryService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.structure.factory']) ? $this->services['sulu_content.structure.factory'] : $this->getSuluContent_Structure_FactoryService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.extension.manager']) ? $this->services['sulu_content.extension.manager'] : $this->getSuluContent_Extension_ManagerService()) && false ?: '_'}, $this->parameters['sulu_content.search.mapping']);
