<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.type.media_selection' shared service.

return $this->services['sulu_media.type.media_selection'] = new \Sulu\Bundle\MediaBundle\Content\Types\MediaSelectionContentType(${($_ = isset($this->services['sulu_media.media_manager']) ? $this->services['sulu_media.media_manager'] : $this->getSuluMedia_MediaManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_media.reference_store.media']) ? $this->services['sulu_media.reference_store.media'] : $this->services['sulu_media.reference_store.media'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()) && false ?: '_'}, 'SuluMediaBundle:Template:content-types/media-selection.html.twig');
