<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.search.subscriber.structure_media' shared service.

return $this->services['sulu_media.search.subscriber.structure_media'] = new \Sulu\Bundle\MediaBundle\Search\Subscriber\StructureMediaSearchSubscriber(${($_ = isset($this->services['sulu_media.media_manager']) ? $this->services['sulu_media.media_manager'] : $this->getSuluMedia_MediaManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.webspace.request_analyzer']) ? $this->services['sulu_core.webspace.request_analyzer'] : $this->getSuluCore_Webspace_RequestAnalyzerService()) && false ?: '_'}, 'sulu-170x170');
