<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.provider.doctrine.factory' shared service.

$this->services['sulu_core.list_builder.metadata.provider.doctrine.factory'] = $instance = new \Metadata\MetadataFactory(${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.doctrine.driver.xml']) ? $this->services['sulu_core.list_builder.metadata.provider.doctrine.driver.xml'] : $this->load('getSuluCore_ListBuilder_Metadata_Provider_Doctrine_Driver_XmlService.php')) && false ?: '_'}, 'Metadata\\ClassHierarchyMetadata', true);

$instance->setCache(${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.doctrine.cache']) ? $this->services['sulu_core.list_builder.metadata.provider.doctrine.cache'] : $this->services['sulu_core.list_builder.metadata.provider.doctrine.cache'] = new \Metadata\Cache\FileCache(($this->targetDirs[0].'/sulu/list-builder/doctrine'))) && false ?: '_'});

return $instance;
