<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.localization_decorator' shared service.

return $this->services['massive_search.localization_decorator'] = new \Massive\Bundle\SearchBundle\Search\Decorator\LocalizationDecorator(${($_ = isset($this->services['massive_search.index_name_decorator']) ? $this->services['massive_search.index_name_decorator'] : $this->load('getMassiveSearch_IndexNameDecoratorService.php')) && false ?: '_'});
