<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.smart_content.data_provider.media' shared service.

return $this->services['sulu_media.smart_content.data_provider.media'] = new \Sulu\Component\Media\SmartContent\MediaDataProvider(${($_ = isset($this->services['sulu_media.smart_content.data_provider.media.repository']) ? $this->services['sulu_media.smart_content.data_provider.media.repository'] : $this->load('getSuluMedia_SmartContent_DataProvider_Media_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_media.collection_manager']) ? $this->services['sulu_media.collection_manager'] : $this->load('getSuluMedia_CollectionManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->getJmsSerializerService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['sulu_media.reference_store.media']) ? $this->services['sulu_media.reference_store.media'] : $this->services['sulu_media.reference_store.media'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()) && false ?: '_'});
