<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.system_collections.manager' shared service.

return $this->services['sulu_media.system_collections.manager'] = new \Sulu\Component\Media\SystemCollections\SystemCollectionManager($this->parameters['sulu_media.system_collections'], ${($_ = isset($this->services['sulu_media.collection_manager']) ? $this->services['sulu_media.collection_manager'] : $this->load('getSuluMedia_CollectionManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, NULL, ${($_ = isset($this->services['sulu_media.system_collections.cache']) ? $this->services['sulu_media.system_collections.cache'] : $this->services['sulu_media.system_collections.cache'] = new \Sulu\Component\Cache\DataCache(($this->targetDirs[0].'/sulu/system_collection.cache'))) && false ?: '_'}, 'en');
