<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.rest.exception_wrapper_handler' shared service.

return $this->services['sulu_core.rest.exception_wrapper_handler'] = new \Sulu\Component\Rest\ExceptionWrapperHandler('dev');
