<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.text_area' shared service.

return $this->services['sulu.content.type.text_area'] = new \Sulu\Component\Content\Types\TextLine('SuluContentBundle:Template:content-types/text_area.html.twig');
