<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.data_collector.sulu_collector' shared service.

return $this->services['sulu_website.data_collector.sulu_collector'] = new \Sulu\Bundle\WebsiteBundle\DataCollector\SuluCollector();
