<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.system_collections.cache' shared service.

return $this->services['sulu_media.system_collections.cache'] = new \Sulu\Component\Cache\DataCache(($this->targetDirs[0].'/sulu/system_collection.cache'));
