<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.jackalope.repository.factory.jackrabbit' shared service.

return $this->services['doctrine_phpcr.jackalope.repository.factory.jackrabbit'] = ${($_ = isset($this->services['doctrine_phpcr.jackalope.repository.factory.service.jackrabbit']) ? $this->services['doctrine_phpcr.jackalope.repository.factory.service.jackrabbit'] : $this->services['doctrine_phpcr.jackalope.repository.factory.service.jackrabbit'] = new \Jackalope\RepositoryFactoryJackrabbit()) && false ?: '_'}->getRepository(array());
