<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.jackalope.repository.factory.doctrinedbal' shared service.

return $this->services['doctrine_phpcr.jackalope.repository.factory.doctrinedbal'] = ${($_ = isset($this->services['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal']) ? $this->services['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] : $this->services['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] = new \Jackalope\RepositoryFactoryDoctrineDBAL()) && false ?: '_'}->getRepository(array());
