<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.factory_default' shared service.

return $this->services['massive_search.factory_default'] = new \Massive\Bundle\SearchBundle\Search\Factory();
