<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.parameter_bag' shared service.

return $this->services['sulu_core.list_builder.metadata.parameter_bag'] = $this->getParameterBag();
