<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.admin_pool' shared service.

$this->services['sulu_admin.admin_pool'] = $instance = new \Sulu\Bundle\AdminBundle\Admin\AdminPool();

$a = ${($_ = isset($this->services['sulu_security.security_checker']) ? $this->services['sulu_security.security_checker'] : $this->getSuluSecurity_SecurityCheckerService()) && false ?: '_'};
$b = ${($_ = isset($this->services['sulu_core.webspace.webspace_manager']) ? $this->services['sulu_core.webspace.webspace_manager'] : $this->getSuluCore_Webspace_WebspaceManagerService()) && false ?: '_'};

$instance->addAdmin(new \Sulu\Bundle\SearchBundle\Admin\SuluSearchAdmin('Sulu'));
$instance->addAdmin(new \Sulu\Bundle\ContactBundle\Admin\ContactAdmin($a, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\MediaBundle\Admin\MediaAdmin($a, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\SecurityBundle\Admin\SecurityAdmin($a, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\CategoryBundle\Admin\CategoryAdmin($a, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\SnippetBundle\Admin\SnippetAdmin($a, $b, true, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\ContentBundle\Admin\ContentAdmin($b, $a, ${($_ = isset($this->services['sulu.phpcr.session']) ? $this->services['sulu.phpcr.session'] : $this->getSulu_Phpcr_SessionService()) && false ?: '_'}, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\TagBundle\Admin\TagAdmin($a, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\WebsiteBundle\Admin\WebsiteAdmin($b, $a, 'Sulu'));
$instance->addAdmin(new \Sulu\Bundle\LocationBundle\Admin\LocationAdmin('Sulu'));
$instance->addAdmin(new \Sulu\Bundle\WebsocketBundle\Admin\WebsocketAdmin());
$instance->addAdmin(new \Sulu\Bundle\DocumentManagerBundle\Admin\DocumentManagerAdmin('Sulu'));
$instance->addAdmin(new \Sulu\Bundle\CustomUrlBundle\Admin\CustomUrlAdmin('Sulu', $b));
$instance->addAdmin(new \Sulu\Bundle\CollaborationBundle\Admin\CollaborationAdmin('Sulu'));
$instance->addAdmin(new \Sulu\Bundle\PreviewBundle\Admin\PreviewAdmin('Sulu'));

return $instance;
