<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_http_cache.proxy_client.symfony' shared service.

return $this->services['sulu_http_cache.proxy_client.symfony'] = new \Sulu\Component\HttpCache\ProxyClient\Symfony();
