<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOl1ope1\websiteDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOl1ope1/websiteDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOl1ope1.legacy');

    return;
}

if (!\class_exists(websiteDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOl1ope1\websiteDevDebugProjectContainer::class, websiteDevDebugProjectContainer::class, false);
}

return new \ContainerOl1ope1\websiteDevDebugProjectContainer(array(
    'container.build_hash' => 'Ol1ope1',
    'container.build_id' => 'b477e0b1',
    'container.build_time' => 1532336290,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOl1ope1');
