<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.admin.live_session' shared service.

return $this->services['doctrine_phpcr.admin.live_session'] = ${($_ = isset($this->services['doctrine_phpcr.admin.jackalope.repository.live']) ? $this->services['doctrine_phpcr.admin.jackalope.repository.live'] : $this->load('getDoctrinePhpcr_Admin_Jackalope_Repository_LiveService.php')) && false ?: '_'}->login(new \PHPCR\SimpleCredentials('admin', 'admin'), NULL);
