<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.expression.evaluator' shared service.

$this->services['hateoas.expression.evaluator'] = $instance = new \Bazinga\Bundle\HateoasBundle\Hateoas\Expression\LazyFunctionExpressionEvaluator(${($_ = isset($this->services['bazinga_hateoas.expression_language']) ? $this->services['bazinga_hateoas.expression_language'] : $this->services['bazinga_hateoas.expression_language'] = new \Bazinga\Bundle\HateoasBundle\ExpressionLanguage\ExpressionLanguage()) && false ?: '_'}, array(), $this);

$instance->setContextVariable('container', $this);
$instance->registerFunctionId('hateoas.expression.link');

return $instance;
