<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_build.command.build' shared service.

return $this->services['massive_build.command.build'] = new \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand(${($_ = isset($this->services['massive_build.build.registry']) ? $this->services['massive_build.build.registry'] : $this->load('getMassiveBuild_Build_RegistryService.php')) && false ?: '_'}, $this);
