<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.twig.area_snippet' shared service.

return $this->services['sulu_snippet.twig.area_snippet'] = new \Sulu\Bundle\SnippetBundle\Twig\SnippetAreaTwigExtension(${($_ = isset($this->services['sulu_snippet.default_snippet.manager']) ? $this->services['sulu_snippet.default_snippet.manager'] : $this->load('getSuluSnippet_DefaultSnippet_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.webspace.request_analyzer']) ? $this->services['sulu_core.webspace.request_analyzer'] : $this->getSuluCore_Webspace_RequestAnalyzerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_snippet.resolver']) ? $this->services['sulu_snippet.resolver'] : $this->load('getSuluSnippet_ResolverService.php')) && false ?: '_'});
