<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_community.build' shared service.

return $this->services['sulu_community.build'] = new \Sulu\Bundle\CommunityBundle\Build\CommunityBuilder();
