<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_search.search.factory' shared service.

return $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory();
