<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.search.event_subscriber.blame_timestamp' shared service.

return $this->services['sulu_content.search.event_subscriber.blame_timestamp'] = new \Sulu\Bundle\ContentBundle\Search\EventSubscriber\BlameTimestampSubscriber(${($_ = isset($this->services['sulu_search.search.factory']) ? $this->services['sulu_search.search.factory'] : $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
