<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.url' shared service.

return $this->services['sulu.content.type.url'] = new \Sulu\Bundle\ContentBundle\Content\Types\Url('SuluContentBundle:Template:content-types/url.html.twig');
