<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_websocket.admin.message_builder' shared service.

return $this->services['sulu_websocket.admin.message_builder'] = new \Sulu\Component\Websocket\MessageDispatcher\MessageBuilder();
