<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.document.subscriber.publish' shared service.

return $this->services['sulu_document_manager.document.subscriber.publish'] = new \Sulu\Bundle\ContentBundle\Document\Subscriber\PublishSubscriber(${($_ = isset($this->services['sulu_document_manager.decorated_live_session']) ? $this->services['sulu_document_manager.decorated_live_session'] : $this->load('getSuluDocumentManager_DecoratedLiveSessionService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.node_helper']) ? $this->services['sulu_document_manager.node_helper'] : $this->services['sulu_document_manager.node_helper'] = new \Sulu\Component\DocumentManager\NodeHelper()) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.property_encoder']) ? $this->services['sulu_document_manager.property_encoder'] : $this->getSuluDocumentManager_PropertyEncoderService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.metadata_factory']) ? $this->services['sulu_document_manager.metadata_factory'] : $this->getSuluDocumentManager_MetadataFactoryService()) && false ?: '_'});
