<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.twig_extension.user.cache' shared service.

return $this->services['sulu_security.twig_extension.user.cache'] = new \Doctrine\Common\Cache\ArrayCache();
