<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.twig_extension' shared service.

return $this->services['sulu_content.twig_extension'] = new \Sulu\Bundle\ContentBundle\Twig\ContentTwigExtension(${($_ = isset($this->services['sulu.content.type_manager']) ? $this->services['sulu.content.type_manager'] : $this->getSulu_Content_TypeManagerService()) && false ?: '_'});
