<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_category.twig_extension' shared service.

return $this->services['sulu_category.twig_extension'] = new \Sulu\Bundle\CategoryBundle\Twig\CategoryTwigExtension(${($_ = isset($this->services['sulu_category.category_manager']) ? $this->services['sulu_category.category_manager'] : $this->load('getSuluCategory_CategoryManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_category.category_request_handler']) ? $this->services['sulu_category.category_request_handler'] : $this->load('getSuluCategory_CategoryRequestHandlerService.php')) && false ?: '_'}, ${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->load('getJmsSerializerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_core.cache.memoize']) ? $this->services['sulu_core.cache.memoize'] : $this->load('getSuluCore_Cache_MemoizeService.php')) && false ?: '_'});
