<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_route.routing.defaults_provider' shared service.

return $this->services['sulu_route.routing.defaults_provider'] = new \Sulu\Bundle\RouteBundle\Routing\Defaults\RouteDefaultsProvider(array(0 => ${($_ = isset($this->services['sulu_content.preview.defaults_provider']) ? $this->services['sulu_content.preview.defaults_provider'] : $this->load('getSuluContent_Preview_DefaultsProviderService.php')) && false ?: '_'}));
