<?php

namespace Proxies\__CG__\Sulu\Bundle\SecurityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Sulu\Bundle\SecurityBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'contact', 'userRoles', 'userGroups', 'userSettings', 'username', 'email', 'password', 'locale', 'id', 'salt', 'privateKey', 'apiKey', 'locked', 'enabled', 'lastLogin', 'confirmationKey', 'passwordResetToken', 'apiBasePath', 'apiPath'];
        }

        return ['__isInitialized__', 'contact', 'userRoles', 'userGroups', 'userSettings', 'username', 'email', 'password', 'locale', 'id', 'salt', 'privateKey', 'apiKey', 'locked', 'enabled', 'lastLogin', 'confirmationKey', 'passwordResetToken', 'apiBasePath', 'apiPath'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addUserRole(\Sulu\Bundle\SecurityBundle\Entity\UserRole $userRoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserRole', [$userRoles]);

        return parent::addUserRole($userRoles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserRole(\Sulu\Bundle\SecurityBundle\Entity\UserRole $userRoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserRole', [$userRoles]);

        return parent::removeUserRole($userRoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRoles', []);

        return parent::getUserRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleObjects', []);

        return parent::getRoleObjects();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserGroup(\Sulu\Bundle\SecurityBundle\Entity\UserGroup $userGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserGroup', [$userGroups]);

        return parent::addUserGroup($userGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserGroup(\Sulu\Bundle\SecurityBundle\Entity\UserGroup $userGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserGroup', [$userGroups]);

        return parent::removeUserGroup($userGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroups', []);

        return parent::getUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserSetting(\Sulu\Bundle\SecurityBundle\Entity\UserSetting $userSettings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserSetting', [$userSettings]);

        return parent::addUserSetting($userSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserSetting(\Sulu\Bundle\SecurityBundle\Entity\UserSetting $userSettings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserSetting', [$userSettings]);

        return parent::removeUserSetting($userSettings);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserSettings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserSettings', []);

        return parent::getUserSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function getSettings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettings', []);

        return parent::getSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(\Sulu\Component\Contact\Model\ContactInterface $contact = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$contact]);

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', [$locale]);

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', []);

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivateKey($privateKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivateKey', [$privateKey]);

        return parent::setPrivateKey($privateKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivateKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivateKey', []);

        return parent::getPrivateKey();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setApiKey($apiKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiKey', [$apiKey]);

        return parent::setApiKey($apiKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiKey', []);

        return parent::getApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($locked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', [$locked]);

        return parent::setLocked($locked);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocked', []);

        return parent::getLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin($lastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', [$lastLogin]);

        return parent::setLastLogin($lastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', []);

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationKey($confirmationKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationKey', [$confirmationKey]);

        return parent::setConfirmationKey($confirmationKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationKey', []);

        return parent::getConfirmationKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetToken($passwordResetToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetToken', [$passwordResetToken]);

        return parent::setPasswordResetToken($passwordResetToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetToken', []);

        return parent::getPasswordResetToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetTokenExpiresAt($passwordResetTokenExpiresAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetTokenExpiresAt', [$passwordResetTokenExpiresAt]);

        return parent::setPasswordResetTokenExpiresAt($passwordResetTokenExpiresAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetTokenExpiresAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetTokenExpiresAt', []);

        return parent::getPasswordResetTokenExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetTokenEmailsSent($passwordResetTokenEmailsSent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetTokenEmailsSent', [$passwordResetTokenEmailsSent]);

        return parent::setPasswordResetTokenEmailsSent($passwordResetTokenEmailsSent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetTokenEmailsSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetTokenEmailsSent', []);

        return parent::getPasswordResetTokenEmailsSent();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinks', []);

        return parent::getLinks();
    }

    /**
     * {@inheritDoc}
     */
    public function createSelfLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createSelfLink', []);

        return parent::createSelfLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getApiPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiPath', []);

        return parent::getApiPath();
    }

    /**
     * {@inheritDoc}
     */
    public function hasApiPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasApiPath', []);

        return parent::hasApiPath();
    }

}
