<?php

namespace Proxies\__CG__\Sulu\Bundle\ContactBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Account extends \Sulu\Bundle\ContactBundle\Entity\Account implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'lft', 'rgt', 'depth', 'children', 'parent', 'addresses', 'urls', 'phones', 'socialMediaProfiles', 'emails', 'notes', 'faxes', 'bankAccounts', 'tags', 'accountContacts', 'accountAddresses', 'medias', 'categories', 'logo', 'apiBasePath', 'apiPath'];
        }

        return ['__isInitialized__', 'lft', 'rgt', 'depth', 'children', 'parent', 'addresses', 'urls', 'phones', 'socialMediaProfiles', 'emails', 'notes', 'faxes', 'bankAccounts', 'tags', 'accountContacts', 'accountAddresses', 'medias', 'categories', 'logo', 'apiBasePath', 'apiPath'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Account $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLft($lft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLft', [$lft]);

        return parent::setLft($lft);
    }

    /**
     * {@inheritDoc}
     */
    public function getLft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLft', []);

        return parent::getLft();
    }

    /**
     * {@inheritDoc}
     */
    public function setRgt($rgt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRgt', [$rgt]);

        return parent::setRgt($rgt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRgt', []);

        return parent::getRgt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepth($depth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepth', [$depth]);

        return parent::setDepth($depth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepth', []);

        return parent::getDepth();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Sulu\Bundle\ContactBundle\Entity\AccountInterface $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function addUrl(\Sulu\Bundle\ContactBundle\Entity\Url $urls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUrl', [$urls]);

        return parent::addUrl($urls);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUrl(\Sulu\Bundle\ContactBundle\Entity\Url $url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUrl', [$url]);

        return parent::removeUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrls', []);

        return parent::getUrls();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhone(\Sulu\Bundle\ContactBundle\Entity\Phone $phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhone', [$phone]);

        return parent::addPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhone(\Sulu\Bundle\ContactBundle\Entity\Phone $phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhone', [$phone]);

        return parent::removePhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhones', []);

        return parent::getPhones();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmail(\Sulu\Bundle\ContactBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmail', [$email]);

        return parent::addEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmail(\Sulu\Bundle\ContactBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmail', [$email]);

        return parent::removeEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmails', []);

        return parent::getEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function addNote(\Sulu\Bundle\ContactBundle\Entity\Note $note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNote', [$note]);

        return parent::addNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNote(\Sulu\Bundle\ContactBundle\Entity\Note $note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNote', [$note]);

        return parent::removeNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', []);

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function addChildren(\Sulu\Bundle\ContactBundle\Entity\AccountInterface $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChildren', [$children]);

        return parent::addChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChildren(\Sulu\Bundle\ContactBundle\Entity\AccountInterface $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChildren', [$children]);

        return parent::removeChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function addFax(\Sulu\Bundle\ContactBundle\Entity\Fax $fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFax', [$fax]);

        return parent::addFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFax(\Sulu\Bundle\ContactBundle\Entity\Fax $fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFax', [$fax]);

        return parent::removeFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaxes', []);

        return parent::getFaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function addSocialMediaProfile(\Sulu\Bundle\ContactBundle\Entity\SocialMediaProfile $socialMediaProfile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSocialMediaProfile', [$socialMediaProfile]);

        return parent::addSocialMediaProfile($socialMediaProfile);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSocialMediaProfile(\Sulu\Bundle\ContactBundle\Entity\SocialMediaProfile $socialMediaProfile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSocialMediaProfile', [$socialMediaProfile]);

        return parent::removeSocialMediaProfile($socialMediaProfile);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialMediaProfiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialMediaProfiles', []);

        return parent::getSocialMediaProfiles();
    }

    /**
     * {@inheritDoc}
     */
    public function addBankAccount(\Sulu\Bundle\ContactBundle\Entity\BankAccount $bankAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBankAccount', [$bankAccount]);

        return parent::addBankAccount($bankAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBankAccount(\Sulu\Bundle\ContactBundle\Entity\BankAccount $bankAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBankAccount', [$bankAccount]);

        return parent::removeBankAccount($bankAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccounts', []);

        return parent::getBankAccounts();
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\Sulu\Bundle\TagBundle\Tag\TagInterface $tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', [$tag]);

        return parent::addTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\Sulu\Bundle\TagBundle\Tag\TagInterface $tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', [$tag]);

        return parent::removeTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function getTagNameArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTagNameArray', []);

        return parent::getTagNameArray();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccountContact(\Sulu\Bundle\ContactBundle\Entity\AccountContact $accountContacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccountContact', [$accountContacts]);

        return parent::addAccountContact($accountContacts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccountContact(\Sulu\Bundle\ContactBundle\Entity\AccountContact $accountContacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccountContact', [$accountContacts]);

        return parent::removeAccountContact($accountContacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountContacts', []);

        return parent::getAccountContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccountAddress(\Sulu\Bundle\ContactBundle\Entity\AccountAddress $accountAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccountAddress', [$accountAddress]);

        return parent::addAccountAddress($accountAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccountAddress(\Sulu\Bundle\ContactBundle\Entity\AccountAddress $accountAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccountAddress', [$accountAddress]);

        return parent::removeAccountAddress($accountAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountAddresses', []);

        return parent::getAccountAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', []);

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function getMainAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainAddress', []);

        return parent::getMainAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\Sulu\Bundle\MediaBundle\Entity\MediaInterface $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', [$media]);

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\Sulu\Bundle\MediaBundle\Entity\MediaInterface $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', [$media]);

        return parent::removeMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', []);

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(\Sulu\Bundle\ContactBundle\Entity\AccountInterface $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', [$children]);

        return parent::addChild($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChild(\Sulu\Bundle\ContactBundle\Entity\AccountInterface $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChild', [$children]);

        return parent::removeChild($children);
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\Sulu\Bundle\CategoryBundle\Entity\CategoryInterface $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$category]);

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\Sulu\Bundle\CategoryBundle\Entity\CategoryInterface $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$category]);

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalId($externalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalId', [$externalId]);

        return parent::setExternalId($externalId);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalId', []);

        return parent::getExternalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorporation($corporation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorporation', [$corporation]);

        return parent::setCorporation($corporation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorporation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorporation', []);

        return parent::getCorporation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', [$uid]);

        return parent::setUid($uid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', []);

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegisterNumber($registerNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegisterNumber', [$registerNumber]);

        return parent::setRegisterNumber($registerNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisterNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisterNumber', []);

        return parent::getRegisterNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceOfJurisdiction($placeOfJurisdiction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceOfJurisdiction', [$placeOfJurisdiction]);

        return parent::setPlaceOfJurisdiction($placeOfJurisdiction);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceOfJurisdiction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceOfJurisdiction', []);

        return parent::getPlaceOfJurisdiction();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainEmail($mainEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainEmail', [$mainEmail]);

        return parent::setMainEmail($mainEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainEmail', []);

        return parent::getMainEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainPhone($mainPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainPhone', [$mainPhone]);

        return parent::setMainPhone($mainPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainPhone', []);

        return parent::getMainPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainFax($mainFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainFax', [$mainFax]);

        return parent::setMainFax($mainFax);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function getMainFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainFax', []);

        return parent::getMainFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainUrl($mainUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainUrl', [$mainUrl]);

        return parent::setMainUrl($mainUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainUrl', []);

        return parent::getMainUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getChanged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanged', []);

        return parent::getChanged();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanged($changed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanged', [$changed]);

        return parent::setChanged($changed);
    }

    /**
     * {@inheritDoc}
     */
    public function getChanger()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanger', []);

        return parent::getChanger();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanger($changer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanger', [$changer]);

        return parent::setChanger($changer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', []);

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator($creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', [$creator]);

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainContact', []);

        return parent::getMainContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainContact($mainContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainContact', [$mainContact]);

        return parent::setMainContact($mainContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinks', []);

        return parent::getLinks();
    }

    /**
     * {@inheritDoc}
     */
    public function createSelfLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createSelfLink', []);

        return parent::createSelfLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getApiPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiPath', []);

        return parent::getApiPath();
    }

    /**
     * {@inheritDoc}
     */
    public function hasApiPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasApiPath', []);

        return parent::hasApiPath();
    }

}
