<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.view_handler' shared service.

$this->services['fos_rest.view_handler'] = $instance = new \FOS\RestBundle\View\ViewHandler($this->parameters['fos_rest.formats'], 400, 204, false, $this->parameters['fos_rest.force_redirects'], 'twig');

$instance->setExclusionStrategyGroups('');
$instance->setExclusionStrategyVersion('');
$instance->setSerializeNullStrategy(false);
$instance->setContainer($this);
$instance->registerHandler('csv', array(0 => ${($_ = isset($this->services['sulu_core.rest.view_handler.csv']) ? $this->services['sulu_core.rest.view_handler.csv'] : $this->load('getSuluCore_Rest_ViewHandler_CsvService.php')) && false ?: '_'}, 1 => 'createResponse'));

return $instance;
