<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.command.status' shared service.

return $this->services['phpcr_migrations.command.status'] = new \DTL\Bundle\PhpcrMigrations\Command\StatusCommand(${($_ = isset($this->services['phpcr_migrations.version_storage']) ? $this->services['phpcr_migrations.version_storage'] : $this->load('getPhpcrMigrations_VersionStorageService.php')) && false ?: '_'}, ${($_ = isset($this->services['phpcr_migrations.version_finder']) ? $this->services['phpcr_migrations.version_finder'] : $this->load('getPhpcrMigrations_VersionFinderService.php')) && false ?: '_'});
