<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.password' shared service.

return $this->services['sulu.content.type.password'] = new \Sulu\Bundle\ContentBundle\Content\Types\Password('SuluContentBundle:Template:content-types/password.html.twig');
