<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.collection_manager' shared service.

return $this->services['sulu_media.collection_manager'] = new \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager(${($_ = isset($this->services['sulu_media.collection_repository']) ? $this->services['sulu_media.collection_repository'] : $this->getSuluMedia_CollectionRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['sulu.repository.media']) ? $this->services['sulu.repository.media'] : $this->getSulu_Repository_MediaService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_media.format_manager']) ? $this->services['sulu_media.format_manager'] : $this->getSuluMedia_FormatManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu.repository.user']) ? $this->services['sulu.repository.user'] : $this->getSulu_Repository_UserService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, NULL, 'sulu-50x50', $this->parameters['sulu_security.permissions']);
