<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.driver.xml' shared service.

return $this->services['massive_search.metadata.driver.xml'] = new \Massive\Bundle\SearchBundle\Search\Metadata\Driver\XmlDriver(${($_ = isset($this->services['sulu_search.search.factory']) ? $this->services['sulu_search.search.factory'] : $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory()) && false ?: '_'}, ${($_ = isset($this->services['massive_search.metadata.file_locator']) ? $this->services['massive_search.metadata.file_locator'] : $this->services['massive_search.metadata.file_locator'] = new \Metadata\Driver\FileLocator(array('Sulu\\Bundle\\ContactBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContactBundle/Resources/config/massive-search'), 'Sulu\\Bundle\\MediaBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\MediaBundle/Resources/config/massive-search'), 'Sulu\\Bundle\\CategoryBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\CategoryBundle/Resources/config/massive-search')))) && false ?: '_'});
