<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_category.reference_store.category' shared service.

return $this->services['sulu_category.reference_store.category'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore();
