<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.content_navigation_provider' shared service.

return $this->services['sulu_snippet.content_navigation_provider'] = new \Sulu\Bundle\SnippetBundle\Admin\SnippetContentNavigationProvider();
