<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.field_descriptor_factory' shared service.

return $this->services['sulu_core.list_builder.field_descriptor_factory'] = new \Sulu\Component\Rest\ListBuilder\Metadata\FieldDescriptorFactory(${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.chain']) ? $this->services['sulu_core.list_builder.metadata.provider.chain'] : $this->load('getSuluCore_ListBuilder_Metadata_Provider_ChainService.php')) && false ?: '_'}, ($this->targetDirs[0].'/sulu/field_descriptor'), true);
