<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.document.subscriber.extension' shared service.

return $this->services['sulu_document_manager.document.subscriber.extension'] = new \Sulu\Component\Content\Document\Subscriber\ExtensionSubscriber(${($_ = isset($this->services['sulu_document_manager.property_encoder']) ? $this->services['sulu_document_manager.property_encoder'] : $this->getSuluDocumentManager_PropertyEncoderService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_content.extension.manager']) ? $this->services['sulu_content.extension.manager'] : $this->getSuluContent_Extension_ManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.document_inspector']) ? $this->services['sulu_document_manager.document_inspector'] : $this->getSuluDocumentManager_DocumentInspectorService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.namespace_registry']) ? $this->services['sulu_document_manager.namespace_registry'] : $this->getSuluDocumentManager_NamespaceRegistryService()) && false ?: '_'});
