<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.content_navigation_controller' shared service.

return $this->services['sulu_admin.content_navigation_controller'] = new \Sulu\Bundle\AdminBundle\Controller\ContentNavigationController(${($_ = isset($this->services['sulu_admin.content_navigation_registry']) ? $this->services['sulu_admin.content_navigation_registry'] : $this->load('getSuluAdmin_ContentNavigationRegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_rest.view_handler']) ? $this->services['fos_rest.view_handler'] : $this->load('getFosRest_ViewHandlerService.php')) && false ?: '_'});
