<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.command.fixtures_load' shared service.

return $this->services['sulu_document_manager.command.fixtures_load'] = new \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand(${($_ = isset($this->services['sulu_document_manager.data_fixtures.loader']) ? $this->services['sulu_document_manager.data_fixtures.loader'] : $this->services['sulu_document_manager.data_fixtures.loader'] = new \Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentFixtureLoader($this)) && false ?: '_'}, ${($_ = isset($this->services['sulu_document_manager.data_fixtures.executor']) ? $this->services['sulu_document_manager.data_fixtures.executor'] : $this->load('getSuluDocumentManager_DataFixtures_ExecutorService.php')) && false ?: '_'}, ${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'});
