<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.preview' shared service.

$a = ${($_ = isset($this->services['sulu_content.preview.object_provider']) ? $this->services['sulu_content.preview.object_provider'] : $this->load('getSuluContent_Preview_ObjectProviderService.php')) && false ?: '_'};

return $this->services['sulu_preview.preview'] = new \Sulu\Bundle\PreviewBundle\Preview\Preview(array('Sulu\\Bundle\\ContentBundle\\Document\\HomeDocument' => $a, 'Sulu\\Bundle\\ContentBundle\\Document\\PageDocument' => $a), ${($_ = isset($this->services['doctrine_cache.providers.sulu_preview']) ? $this->services['doctrine_cache.providers.sulu_preview'] : $this->services['doctrine_cache.providers.sulu_preview'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/sulu/preview'), NULL, 2)) && false ?: '_'}, ${($_ = isset($this->services['sulu_preview.preview.renderer']) ? $this->services['sulu_preview.preview.renderer'] : $this->load('getSuluPreview_Preview_RendererService.php')) && false ?: '_'});
