<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.authentication_entry_point' shared service.

return $this->services['sulu_security.authentication_entry_point'] = new \Sulu\Bundle\SecurityBundle\Security\AuthenticationEntryPoint(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
