<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.multiple_select' shared service.

return $this->services['sulu.content.type.multiple_select'] = new \Sulu\Bundle\ContentBundle\Content\Types\MultipleSelect('SuluContentBundle:Template:content-types/multiple_select.html.twig');
