<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.provider.general' shared service.

return $this->services['sulu_core.list_builder.metadata.provider.general'] = new \Sulu\Component\Rest\ListBuilder\Metadata\Provider\MetadataProvider(${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.general.factory']) ? $this->services['sulu_core.list_builder.metadata.provider.general.factory'] : $this->load('getSuluCore_ListBuilder_Metadata_Provider_General_FactoryService.php')) && false ?: '_'});
