<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.salt_generator' shared service.

return $this->services['sulu_security.salt_generator'] = new \Sulu\Component\Security\Authentication\SaltGenerator();
