<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.subscriber.phpcr.reorder' shared service.

return $this->services['sulu_document_manager.subscriber.phpcr.reorder'] = new \Sulu\Component\DocumentManager\Subscriber\Phpcr\ReorderSubscriber(${($_ = isset($this->services['sulu_document_manager.node_helper']) ? $this->services['sulu_document_manager.node_helper'] : $this->services['sulu_document_manager.node_helper'] = new \Sulu\Component\DocumentManager\NodeHelper()) && false ?: '_'});
