<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.js_config' shared service.

return $this->services['sulu_preview.js_config'] = new \Sulu\Bundle\AdminBundle\Admin\JsConfig('sulu_preview', array('mode' => 'auto', 'delay' => 500));
