<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.smart_content.data_provider.content.proxy_factory' shared service.

return $this->services['sulu_content.smart_content.data_provider.content.proxy_factory'] = new \ProxyManager\Factory\LazyLoadingValueHolderFactory(${($_ = isset($this->services['sulu_core.proxy_manager.configuration']) ? $this->services['sulu_core.proxy_manager.configuration'] : $this->getSuluCore_ProxyManager_ConfigurationService()) && false ?: '_'});
