<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.js_config' shared service.

return $this->services['sulu_security.js_config'] = new \Sulu\Bundle\SecurityBundle\Security\SecurityConfig('sulu_security.contexts', ${($_ = isset($this->services['sulu_security.access_control_manager']) ? $this->services['sulu_security.access_control_manager'] : $this->load('getSuluSecurity_AccessControlManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sulu_admin.admin_pool']) ? $this->services['sulu_admin.admin_pool'] : $this->load('getSuluAdmin_AdminPoolService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'});
