<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.webspace.url_provider' shared service.

return $this->services['sulu_core.webspace.url_provider'] = new \Sulu\Component\Webspace\Url\WebspaceUrlChainProvider(array(0 => ${($_ = isset($this->services['sulu_core.webspace.url_provider.default']) ? $this->services['sulu_core.webspace.url_provider.default'] : $this->services['sulu_core.webspace.url_provider.default'] = new \Sulu\Component\Webspace\Url\WebspaceUrlProvider()) && false ?: '_'}, 1 => ${($_ = isset($this->services['sulu_custom_urls.url_provider']) ? $this->services['sulu_custom_urls.url_provider'] : $this->load('getSuluCustomUrls_UrlProviderService.php')) && false ?: '_'}));
