<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.default_session' shared service.

return $this->services['doctrine_phpcr.default_session'] = ${($_ = isset($this->services['doctrine_phpcr.jackalope.repository.default']) ? $this->services['doctrine_phpcr.jackalope.repository.default'] : $this->load('getDoctrinePhpcr_Jackalope_Repository_DefaultService.php')) && false ?: '_'}->login(new \PHPCR\SimpleCredentials('admin', 'admin'), 'default');
