<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.jackalope.repository.factory.prismic' shared service.

return $this->services['doctrine_phpcr.jackalope.repository.factory.prismic'] = ${($_ = isset($this->services['doctrine_phpcr.jackalope.repository.factory.service.prismic']) ? $this->services['doctrine_phpcr.jackalope.repository.factory.service.prismic'] : $this->services['doctrine_phpcr.jackalope.repository.factory.service.prismic'] = new \Jackalope\RepositoryFactoryPrismic()) && false ?: '_'}->getRepository(array());
