<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.routing.loader.yaml_collection' shared service.

return $this->services['fos_rest.routing.loader.yaml_collection'] = new \FOS\RestBundle\Routing\Loader\RestYamlCollectionLoader(${($_ = isset($this->services['file_locator']) ? $this->services['file_locator'] : $this->services['file_locator'] = new \Symfony\Component\HttpKernel\Config\FileLocator(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'}, ($this->targetDirs[4].'\\app/Resources'), array(0 => ($this->targetDirs[4].'\\app')))) && false ?: '_'}, ${($_ = isset($this->services['fos_rest.routing.loader.processor']) ? $this->services['fos_rest.routing.loader.processor'] : $this->services['fos_rest.routing.loader.processor'] = new \FOS\RestBundle\Routing\Loader\RestRouteProcessor()) && false ?: '_'}, true, $this->parameters['fos_rest.formats'], 'json');
