<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.command.purge' shared service.

return $this->services['massive_search.command.purge'] = new \Massive\Bundle\SearchBundle\Command\PurgeCommand(${($_ = isset($this->services['massive_search.search_manager']) ? $this->services['massive_search.search_manager'] : $this->load('getMassiveSearch_SearchManagerService.php')) && false ?: '_'});
