<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.adapter.zend_lucene' shared service.

return $this->services['massive_search.adapter.zend_lucene'] = new \Massive\Bundle\SearchBundle\Search\Adapter\ZendLuceneAdapter(${($_ = isset($this->services['sulu_search.search.factory']) ? $this->services['sulu_search.search.factory'] : $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory()) && false ?: '_'}, ($this->targetDirs[3].'/indexes'), ${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : $this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()) && false ?: '_'}, false, 'UTF-8');
