<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.reindex.provider.doctrine_orm' shared service.

return $this->services['massive_search.reindex.provider.doctrine_orm'] = new \Massive\Bundle\SearchBundle\Search\Reindex\Provider\DoctrineOrmProvider(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['massive_search.metadata.factory']) ? $this->services['massive_search.metadata.factory'] : $this->load('getMassiveSearch_Metadata_FactoryService.php')) && false ?: '_'});
