<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.converter' shared service.

$this->services['massive_search.converter'] = $instance = new \Massive\Bundle\SearchBundle\Search\Converter\ConverterManager();

$instance->addConverter('date', ${($_ = isset($this->services['massive_search.converter.date_converter']) ? $this->services['massive_search.converter.date_converter'] : $this->services['massive_search.converter.date_converter'] = new \Massive\Bundle\SearchBundle\Search\Converter\Types\DateConverter()) && false ?: '_'});
$instance->addConverter('json', ${($_ = isset($this->services['massive_search.converter.json_converter']) ? $this->services['massive_search.converter.json_converter'] : $this->services['massive_search.converter.json_converter'] = new \Massive\Bundle\SearchBundle\Search\Converter\Types\JsonConverter()) && false ?: '_'});
$instance->addConverter('tags', ${($_ = isset($this->services['sulu_tag.search.tags_converter']) ? $this->services['sulu_tag.search.tags_converter'] : $this->load('getSuluTag_Search_TagsConverterService.php')) && false ?: '_'});

return $instance;
