<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.file_locator' shared service.

return $this->services['massive_search.metadata.file_locator'] = new \Metadata\Driver\FileLocator(array('Sulu\\Bundle\\ContactBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\ContactBundle/Resources/config/massive-search'), 'Sulu\\Bundle\\MediaBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\MediaBundle/Resources/config/massive-search'), 'Sulu\\Bundle\\CategoryBundle\\Entity' => ($this->targetDirs[4].'\\vendor\\sulu\\sulu\\src\\Sulu\\Bundle\\CategoryBundle/Resources/config/massive-search')));
