<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.version_storage' shared service.

return $this->services['phpcr_migrations.version_storage'] = new \PHPCR\Migrations\VersionStorage(${($_ = isset($this->services['doctrine_phpcr.default_session']) ? $this->services['doctrine_phpcr.default_session'] : $this->load('getDoctrinePhpcr_DefaultSessionService.php')) && false ?: '_'}, 'jcr:versions');
