<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.security_context' shared service.

return $this->services['sulu_media.security_context'] = new \Sulu\Component\Security\Authorization\SecurityCondition('sulu.media.collections');
