<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_community.mail_listener' shared service.

return $this->services['sulu_community.mail_listener'] = new \Sulu\Bundle\CommunityBundle\EventListener\MailListener(${($_ = isset($this->services['sulu_community.mail_factory']) ? $this->services['sulu_community.mail_factory'] : $this->load('getSuluCommunity_MailFactoryService.php')) && false ?: '_'});
