<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.suscriber.behavior.timestamp' shared service.

return $this->services['sulu_document_manager.suscriber.behavior.timestamp'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Audit\TimestampSubscriber(${($_ = isset($this->services['sulu_document_manager.property_encoder']) ? $this->services['sulu_document_manager.property_encoder'] : $this->getSuluDocumentManager_PropertyEncoderService()) && false ?: '_'});
