<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_category.content.type.category_list' shared service.

return $this->services['sulu_category.content.type.category_list'] = new \Sulu\Bundle\CategoryBundle\Content\Types\CategoryList(${($_ = isset($this->services['sulu_category.category_manager']) ? $this->services['sulu_category.category_manager'] : $this->getSuluCategory_CategoryManagerService()) && false ?: '_'}, 'SuluCategoryBundle:Template:content-types/category_list.html.twig');
