<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.rl_repository' shared service.

return $this->services['sulu_content.rl_repository'] = new \Sulu\Bundle\ContentBundle\Repository\ResourceLocatorRepository(${($_ = isset($this->services['sulu.content.resource_locator.strategy_pool']) ? $this->services['sulu.content.resource_locator.strategy_pool'] : $this->getSulu_Content_ResourceLocator_StrategyPoolService()) && false ?: '_'}, ${($_ = isset($this->services['sulu.content.structure_manager']) ? $this->services['sulu.content.structure_manager'] : $this->getSulu_Content_StructureManagerService()) && false ?: '_'});
