<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.jsconfig' shared service.

return $this->services['sulu_snippet.jsconfig'] = new \Sulu\Bundle\AdminBundle\Admin\JsConfig('sulu-snippet', array('defaultType' => 'default'));
