<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.provider.chain' shared service.

return $this->services['sulu_core.list_builder.metadata.provider.chain'] = new \Sulu\Component\Rest\ListBuilder\Metadata\Provider\ChainProvider(array(0 => ${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.general']) ? $this->services['sulu_core.list_builder.metadata.provider.general'] : $this->load('getSuluCore_ListBuilder_Metadata_Provider_GeneralService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['sulu_core.list_builder.metadata.provider.doctrine']) ? $this->services['sulu_core.list_builder.metadata.provider.doctrine'] : $this->load('getSuluCore_ListBuilder_Metadata_Provider_DoctrineService.php')) && false ?: '_'}));
