<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_websocket.fallback_controller' shared service.

return $this->services['sulu_websocket.fallback_controller'] = new \Sulu\Bundle\WebsocketBundle\Controller\FallbackController(${($_ = isset($this->services['sulu_websocket.manager']) ? $this->services['sulu_websocket.manager'] : $this->services['sulu_websocket.manager'] = new \Sulu\Component\Websocket\RatchetAppManager(587, 'imap.derprovider.at', '0.0.0.0')) && false ?: '_'});
