<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_location.map_manager' shared service.

$this->services['sulu_location.map_manager'] = $instance = new \Sulu\Bundle\LocationBundle\Map\MapManager();

$instance->registerProvider('leaflet', array('title' => 'Leaflet (OSM)'));
$instance->registerProvider('google', array('title' => 'Google Maps', 'api_key' => NULL));
$instance->registerGeolocator('nominatim', array('endpoint' => 'http://open.mapquestapi.com/nominatim/v1/search.php'));
$instance->registerGeolocator('google', array('api_key' => ''));
$instance->setDefaultProviderName('leaflet');

return $instance;
