<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.search.subscriber.media' shared service.

return $this->services['sulu_media.search.subscriber.media'] = new \Sulu\Bundle\MediaBundle\Search\Subscriber\MediaSearchSubscriber(${($_ = isset($this->services['sulu_media.media_manager']) ? $this->services['sulu_media.media_manager'] : $this->getSuluMedia_MediaManagerService()) && false ?: '_'}, ${($_ = isset($this->services['sulu_search.search.factory']) ? $this->services['sulu_search.search.factory'] : $this->services['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory()) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'}, $this->parameters['sulu_media.format_manager.mime_types'], 'sulu-170x170');
