<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_content.document.serializer.subscriber.redirect_type_behavior' shared service.

return $this->services['sulu_content.document.serializer.subscriber.redirect_type_behavior'] = new \Sulu\Bundle\ContentBundle\Serializer\Subscriber\RedirectTypeSubscriber();
