<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu.content.type.checkbox' shared service.

return $this->services['sulu.content.type.checkbox'] = new \Sulu\Bundle\ContentBundle\Content\Types\Checkbox('SuluContentBundle:Template:content-types/checkbox.html.twig');
