<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.build.user' shared service.

return $this->services['sulu_security.build.user'] = new \Sulu\Bundle\SecurityBundle\Build\UserBuilder();
